spring:
  cloud:
    gateway:
      routes:
#        - id: SECURITY-FIRE-SAFETY
#          # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
#          uri: lb://SECURITY-FIRE-SAFETY
#          predicates:
#            # 重点！转发该路径！
#            - Path=/firesafety/**
#          filters:
#            - StripPrefix=1
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: gateway-${random.value}
    instance-id: ${eureka.instance.hostname}:${server.port}:@project.version@
    ip-address: ${INSTANCE_IP:localhost}
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    lease-expiration-duration-in-seconds: 2
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30S
    lease-renewal-interval-in-seconds: 1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${REGISTER_URL:http://192.168.25.201:8762/eureka/,http://192.168.25.201:8763/eureka/}
    healthcheck:
      enabled: true
    ##eureka client刷新本地缓存时间
    # 默认30s
    registryFetchIntervalSeconds: 5