server:
  port: ${SERVER_PORT:8802}
spring:
  application:
    name: ${APPLICATION_NAME:qitech-demo}
  profiles:
    active: ${PROFILE_ACTIVE:dev}
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis-plus:
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: UUID
      # 表名、是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: true
      # 逻辑已删除值(默认为 1)
      #logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      #logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml


logging:
  config: classpath:config/logback.xml
  # 打印sql
  level:
    com.qitech.mybatis.mapper : debug