server:
  port: 8000

logging:
  level:
    org:
      springframework:
        security: DEBUG


application:
  security:
    oauth:
      client[0]:
        registered-redirect-uri: http://example.com
        # 客户端 id
        client-id: web
        # 客户端密钥
        client-secret: websecret
        # 授权范围
        scope: all
        # token 有效期
        access-token-validity-seconds: 6000
        # 刷新 token 的有效期
        refresh-token-validity-seconds: 6000
        # 允许的授权类型
        authorized_grant_types: authorization_code,password,refresh_token
        # 可以访问的资源 id
        resource-ids: oauth2
      client[1]:
        registered-redirect-uri: http://example.com
        # 客户端 id
        client-id: app
        # 客户端密钥
        client-secret: appsecret
        # 授权范围
        scope: all
        # token 有效期
        access-token-validity-seconds: 6000
        # 刷新 token 的有效期
        refresh-token-validity-seconds: 6000
        # 允许的授权类型
        authorized_grant_types: authorization_code,password,refresh_token
        # 可以访问的资源 id
        resource-ids: oauth2
